#!/bin/bash
# =============================================================================
# Android Code Signing Automation Script
# Project: LexTrack Mobile
# Author: DevOps Engineer (Paperclip)
# =============================================================================
#
# Usage:
#   ./scripts/ci/setup-android-signing.sh [staging|production]
#
# Required environment variables:
#   ANDROID_KEYSTORE_BASE64   — base64-encoded release.keystore
#   ANDROID_KEYSTORE_PASSWORD — keystore password
#   ANDROID_KEY_PASSWORD      — key password
#   ANDROID_KEY_ALIAS         — key alias
#
# =============================================================================

set -euo pipefail

ENVIRONMENT="${1:-staging}"
ANDROID_DIR="android/app"
KEYSTORE_FILE="${ANDROID_DIR}/release.keystore"

echo "=== Android Code Signing Setup ==="
echo "Environment: ${ENVIRONMENT}"
echo ""

# Validate required env vars
for var in ANDROID_KEYSTORE_BASE64 ANDROID_KEYSTORE_PASSWORD ANDROID_KEY_PASSWORD ANDROID_KEY_ALIAS; do
  if [ -z "${!var:-}" ]; then
    echo "ERROR: Environment variable ${var} is not set" >&2
    exit 1
  fi
done

# Decode keystore
echo "[1/4] Decoding keystore..."
echo "${ANDROID_KEYSTORE_BASE64}" | base64 -d > "${KEYSTORE_FILE}"
chmod 600 "${KEYSTORE_FILE}"

# Create/Update local.properties
echo "[2/4] Updating local.properties..."
cat > android/local.properties <<EOF
sdk.dir=/usr/local/lib/android/sdk
ndk.dir=/usr/local/lib/android/ndk
EOF

# Create/Update gradle.properties signing config
echo "[3/4] Setting up gradle.properties..."
cat >> android/gradle.properties <<EOF

# Auto-generated by CI — do not commit
LEXTRACK_RELEASE_STORE_FILE=release.keystore
LEXTRACK_RELEASE_STORE_PASSWORD=${ANDROID_KEYSTORE_PASSWORD}
LEXTRACK_RELEASE_KEY_ALIAS=${ANDROID_KEY_ALIAS}
LEXTRACK_RELEASE_KEY_PASSWORD=${ANDROID_KEY_PASSWORD}
EOF

# Verify keystore
echo "[4/4] Verifying keystore..."
keytool -list -v \
  -keystore "${KEYSTORE_FILE}" \
  -storepass "${ANDROID_KEYSTORE_PASSWORD}" \
  -alias "${ANDROID_KEY_ALIAS}" > /dev/null 2>&1

echo ""
echo "✅ Android code signing configured successfully!"
echo "Keystore: ${KEYSTORE_FILE}"
echo "Alias: ${ANDROID_KEY_ALIAS}"
echo "Environment: ${ENVIRONMENT}"

# Show certificate info (sanitized)
echo ""
echo "=== Certificate Info ==="
keytool -list -keystore "${KEYSTORE_FILE}" \
  -storepass "${ANDROID_KEYSTORE_PASSWORD}" \
  -alias "${ANDROID_KEY_ALIAS}" 2>/dev/null | grep -E "(Valid from|Serial number|SHA1|SHA256)" || true